[general]
import = [
    "~/.config/alacritty/themes/themes/kitty.toml"
]

[font]
size = 15.25
#normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
#normal = { family = "VictorMono Nerd Font Mono", style = "Regular" }
#normal = { family = "Agave Nerd Font Mono", style = "Regular" }
#normal = { family = "GeistMono Nerd Font Mono", style = "Regular" }
#normal = { family = "Hack Nerd Font Mono", style = "Regular" }
#normal = { family = "MesloLGM Nerd Font Mono", style = "Regular" }
#normal = { family = "ProFontWindows Nerd Font Mono", style = "Regular" }
#normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
normal = { family = "SpaceMono Nerd Font Mono", style = "Regular" }

[window]
option_as_alt = "Both"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
